### ISSUE TITLE
Problem with synchronization/triangulation

### ISSUE THREAD

**Issue by Kamu0209** [perfanalytics/pose2sim#106]
Hello,

I have a Problem with the workstep Synchronization/Triangulation.
1. The Syncro is not working, if I try it for the first Time in a Trial

![image](https://github.com/perfanalytics/pose2sim/assets/116355651/4d256e7c-87a6-4a0c-9417-e360fff1f24b)

![image](https://github.com/perfanalytics/pose2sim/assets/116355651/3e11bff0-7b1f-4cff-a81e-19701333e79a)

Maybe its because my calibration output is different from the tutorial:

![image](https://github.com/perfanalytics/pose2sim/assets/116355651/24b351b4-905f-4e17-a447-597b9b9225bc)

I´m using EasyMocap to calibrate my cams and I changed toml file to "Convert" and "Easymocap"

2. 

The output for the personAssociation looks like this:

![image](https://github.com/perfanalytics/pose2sim/assets/116355651/86be9b2d-1018-4898-8e95-f8cc0a67c40f)

Afterwards the Triangulation does not work and I don´t know why:(

![image](https://github.com/perfanalytics/pose2sim/assets/116355651/ca81bb09-6c1e-483e-880f-21cc9ccf21e0)

**Comment by Kamu0209** [comment]
Problem solved!!!

Deleted other Trial/Batch Folder

**Comment by davidpagnon** [comment]
I love it when it is solved without my help 😁
Would you mind telling me what went wrong, in case some other users face it?

**Comment by Kamu0209** [comment]
I am not sure. I thought i don´t work because the calibration was bad. I ve only deleted other Folder Batch/Trial Folder , so that i only have one folder with the needed structure and of course i ve selected only the trial folder in anaconda

![image](https://github.com/perfanalytics/pose2sim/assets/116355651/b393f37f-d9ce-48b2-bbf4-2599f34e5a7d)

**Comment by Kamu0209** [comment]
The Cause was I have changed the personAssociation Parameters in the config.toml and now it is working (likelihood_threshold_association and reproj_error_threshold_association)

**Comment by davidpagnon** [comment]
Nice, thanks your for following up!
