### ISSUE TITLE
Did the expected format of json change with latest 0.9 version ? 

### ISSUE THREAD

**Issue by ANaaim** [perfanalytics/pose2sim#117]
Hi, 

I was wondering if the format of the expected json was changed in latest version (0.9)? 

Best regards,

**Comment by davidpagnon** [comment]
It shouldn't do you experience any issue?

The main difference is that we don't use body_25 or body_25B openpose models anymore, but Halpe_26, which uses a different keypoint ordering.

**Comment by davidpagnon** [comment]
You're right, I messed it up, thank you for spotting it!
I'll fix it right now

**Comment by ANaaim** [comment]
Cool. so no need to copy the data from a the pose folder to a pose-associated ?

**Comment by davidpagnon** [comment]
Can you confirm that it works with the last patch on triangulation.py?
You should not have to copy anything, no.

**Comment by ANaaim** [comment]
i should do a pip update pose2sim ?

**Comment by ANaaim** [comment]
I will test this.

**Comment by ANaaim** [comment]
it work with the new version of triangulation. Let me know when it is integrated in the pip install

**Comment by ANaaim** [comment]
Hi David, did you integrate the modif in a new version that can be installed with pip ? 

Thanks.

**Comment by davidpagnon** [comment]
Hi, 
Sorry I initially wanted to wait until more changes were made but it does not make sense, I just pushed the last release to pypi
