### ISSUE TITLE
Bug when assign start frame nonzero

### ISSUE THREAD

**Issue by wangshubo90** [perfanalytics/pose2sim#13]
If user assigns a nonzero start frame, an exception will be encountered. 

How to fix it:

triangulate_3d.py

line 147
    Q.index = np.array(range(f_range[0]-f_range[0], f_range[1]-f_range[0])) + 1
line 397 
    f_range = [[0,min([len(j) for j in json_files_names])] if frame_range==[] else [i - min(frame_range) for i in frame_range]][0]
line 436
     trc_path = make_trc(config, Q_tot, keypoints_names, frame_range)

**Comment by davidpagnon** [comment]
Hi, thank you for pointing this out, and for offering a fix! 
Sorry for the day of delay, I had to run a few tests to make sure it worked as expected, and it does!

I just released a new version with your changes, you can install it with `pip install pose2sim --upgrade`
