### ISSUE TITLE
Issue with Qualisys data

### ISSUE THREAD

**Issue by mickaelbegon** [perfanalytics/pose2sim#31]
Dear David, 

We tried Pose2Sim with 2 different Qualisys systems (Lyon and Montréal).
The triangulation does not work, probably due to the calibration conversion. 
Removing /64 fix partly the problem. Could you please explain to us where the 64 comes from or other documents explaining the conversion?
Regards!
mickael

**Comment by mickaelbegon** [comment]
Ok pour the /64. 
Between past and new calibrations, it looks like that U and V have been inverted. We try a few things ... 
Value of Bottom became value of Right 


<fov_marker bottom="1919" left="0" right="1087" top="0"/>
<fov_marker left="0" top="0" right="1919" bottom="1087"/>

centerPointU="34110.316406"   vs centerPointU="61425.429688" 
centerPointV="60680.792969"  vs  centerPointV="35247.296875" 

we explore this idea

**Comment by davidpagnon** [comment]
I'm not sure I understand it all, but just in case, are your cameras in portrait mode?
If so, you will need to rotate your videos for OpenPose/AlphaPose/etc to work, but you will then have to "rotate" your calibration file. 

If this is the case, there is a little bit of work to be done:
- run Pose2Sim.calibration() normally
- use [rotate_cams](https://github.com/perfanalytics/pose2sim/blob/184811594e9969730f9583de886218aea9c961f6/Pose2Sim/common.py#L158) this way: 
  ```
  r,t=rotate_cam(Calib_toml_rot, Calib_toml_trans, ang_z=3*np.pi/2)
  r=np.squeeze(cv2.Rodrigues(r)[0])
  print(r,t)```
- switch sizeH and sizeW in your Calib.toml file
- also switch cu and cv

**Comment by davidpagnon** [comment]
@mickaelbegon Any news on this end?

**Comment by mickaelbegon** [comment]
@davidpagnon. We found our mistake. Thank you for your time. You can close this issue. 
Regards
Mickael

**Comment by lishuaifu** [comment]
Hello, I want to know how to export the .qca.txt file of Quaanalysis, I think I can only get .qca file
