### ISSUE TITLE
Strange behavior when calculating the extrinsics calibration with the results : 

### ISSUE THREAD

**Issue by ANaaim** [perfanalytics/pose2sim#48]
When doing my extrinsic calibration using checkerboard the RMS in mm seems... strange. I know that our checkerboard might be too small for our set up, but the error found are quite huge.

![image](https://github.com/perfanalytics/pose2sim/assets/33746865/6e47376d-b56f-4446-9d3a-19523b5c45a0)
==> If 1px of error generate 1.5m of error i would be quite flabbergasted. 

Do you think it might be due to an error in the caculation ? If yes, i can do some investigation 🕵️

Thanks :)

**Comment by davidpagnon** [comment]
Oh I think it is a unit error 😅

In Config.toml, objp is in m when detected from points in scene, and in mm when it is detected from a checkerboard (extrinsics_square_size = 60 # mm). I probably did not do the conversion in this second case... 

Beware that the same function findCorners is used both for extrinsics and intrinsics, so it is important to make sure a fix on extrinsics does not break the intrinsics. (I have not checked, in this case it may not be a problem).

**Comment by ANaaim** [comment]
Ok i am on it !

**Comment by ANaaim** [comment]
Question : Where should be the correction ? at the surface in the config file or in the function calibrate_intrinsics.py and calibrate_extrinsics.py with the following code (here as an example in ): 

```python
    try:
        intrinsics_cam_listdirs_names = next(os.walk(os.path.join(calib_dir, 'intrinsics')))[1]
    except StopIteration:
        logging.exception(f'Error: No {os.path.join(calib_dir, "intrinsics")} folder found.')
        raise Exception(f'Error: No {os.path.join(calib_dir, "intrinsics")} folder found.')
    intrinsics_extension = intrinsics_config_dict.get('intrinsics_extension')
    extract_every_N_sec = intrinsics_config_dict.get('extract_every_N_sec')
    overwrite_extraction = False
    show_detection_intrinsics = intrinsics_config_dict.get('show_detection_intrinsics')
    intrinsics_corners_nb = intrinsics_config_dict.get('intrinsics_corners_nb')
    intrinsics_square_size = intrinsics_config_dict.get('intrinsics_square_size') / 1000 # convert to meters
    ret, C, S, D, K, R, T = [], [], [], [], [], [], []
```

With this correction on both function i have following results which seems more coherent : 


If it is ok for you i do a PR. 
![image](https://github.com/perfanalytics/pose2sim/assets/33746865/940c03eb-c085-4f4b-af04-25e855015edb)

**Comment by davidpagnon** [comment]
Thanks Alexandre! I will probably wait until the weekend to check and merge pull requests, so feel free to experiment as much as you want 😊

**Comment by ANaaim** [comment]
For me it seems to work like this, information are written everywhere, input from user are logical from them and the transformation from mm to m is done in a logical place so seems pretty fair :) I can integrate it in my current PR if ok fro you.

**Comment by davidpagnon** [comment]
Sure, thanks!
