### ISSUE TITLE
.qca.txt

### ISSUE THREAD

**Issue by lishuaifu** [perfanalytics/pose2sim#56]
Hello, I want to know how to export the .qca.txt file of Quaanalysis, I think I can only get .qca file

**Comment by davidpagnon** [comment]
Hi, I'm not sure as I do not use QTM myself, but could you try to just add a ".txt" at the end of the filename?

**Comment by davidpagnon** [comment]
Hi, I'm not sure as I do not use QTM myself, but could you try to just add a ".txt" at the end of the filename?

**Comment by lishuaifu** [comment]
Hello, I'm sorry. I tried this method, and after opening it, there was garbled code

**Comment by davidpagnon** [comment]
I am not sure then, sorry... There must be an option to export calibration in the Qualisys software since many others have done it, but right now I cannot check it since I don't have access to the software...
When you find it, can you answer here so that I add the precise explanation to the tutorial?

**Comment by lishuaifu** [comment]
No problem. I'll check again


---Original---
From: "David ***@***.***&gt;
Date: Wed, Dec 13, 2023 22:00 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [perfanalytics/pose2sim] .qca.txt (Issue #56)




 
I am not sure then, sorry... There must be an option to export calibration in the Qualisys software since many others have done it, but right now I cannot check it since I don't have access to the software...
 When you find it, can you answer here so that I add the precise explanation to the tutorial?

**Comment by ANaaim** [comment]
I think that when you export the calibration you can add the txt at the end : 
![image](https://github.com/perfanalytics/pose2sim/assets/33746865/e7b176e6-89b2-471a-9aa1-8a1f27642406)
then : 
![image](https://github.com/perfanalytics/pose2sim/assets/33746865/96e51fdc-91a3-49a9-99e9-fca9fb9700a8)

**Comment by davidpagnon** [comment]
Thanks Alexandre! 
@lishuaifu here is the solution :)

**Comment by lishuaifu** [comment]
Thank you very much. I'll try it




---Original---
From: "Alexandre ***@***.***&gt;
Date: Thu, Dec 14, 2023 22:17 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [perfanalytics/pose2sim] .qca.txt (Issue #56)




 
I think that when you export the calibration you can add the txt at the end :
 image.png (view on web)
 then :
 image.png (view on web)

**Comment by lishuaifu** [comment]
Thank you very much. I also export from this interface before, I did not want to add .txt suffix at the end, I will try again！



---Original---
From: "David ***@***.***&gt;
Date: Fri, Dec 15, 2023 05:32 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [perfanalytics/pose2sim] .qca.txt (Issue #56)




 
Thanks Alexandre!
 @lishuaifu here is the solution :)
