### ISSUE TITLE
Latest release is broken?

### ISSUE THREAD

**Issue by UdolfSeelenfrost** [perfanalytics/pose2sim#60]
I just pulled the repository and upgraded Pose2Sim to the latest version 0.5.3. Unfortunately this new version isn't working for me. When trying to do the tutorial (Demonstration Part-1) i get the following error:
![WithLimbSwapping](https://github.com/perfanalytics/pose2sim/assets/71120700/6ff29fa2-b83a-480b-8815-de8b41a8095b)

I thought i may be because of the recently added limb swapping, but when I disable it in config.toml I just get another error:
![WithoutLimbSwapping](https://github.com/perfanalytics/pose2sim/assets/71120700/ea06d1ef-68bf-4f00-98cd-16a57734fbfb)

I get the same behavior with data that has previously worked. I will just work with an older version until this is fixed.

**Comment by davidpagnon** [comment]
Sorry yes, it is broken due to the last push I did this afternoon in order to better handle lens distortions, I should have used the draft branch but I got confused. I'll fix it in the evening!

**Comment by UdolfSeelenfrost** [comment]
Nice, thank you. The new folder structure looks good, I want to use it.

**Comment by davidpagnon** [comment]
Hi there, it should be fixed but please leave the parameter `undistort_points` to false in Config.toml, I still have a few issues when handling distortions.

**Comment by UdolfSeelenfrost** [comment]
Haven't tested it but I trust you
