### ISSUE TITLE
Question related to Static Pose

### ISSUE THREAD

**Issue by gokcergun** [perfanalytics/pose2sim#68]
I am wondering if the Sim2 system would be compatible with sitting postures. I have an old recording captured with 12 cameras, featuring a sitting posture. I do not have any T-Pose recordings, but I can identify a frame that serves as a T-Pose while in a sitting posture. Would this work? Or should the static pose be standing?

Thank you.

**Comment by davidpagnon** [comment]
It should not be a person blem as long as keypoints are correctly detected, the person just needs to be static for a few frames. I've actually done the scaling on one frame with a moving person, it's not ideal but results don't look bad.

**Comment by gokcergun** [comment]
Great, thank you. Yes, I thought the same, one frame can be replicated.
