### ISSUE TITLE
[Pose2Sim Setup] OpenSim Scale Model "Unable to open marker file"

### ISSUE THREAD

**Issue by mattorga** [perfanalytics/pose2sim#69]
When I try to load the given scaling file `Scaling_Setup_Pose2Sim_LSTM.xml`, OpenSim outputs an error message: 
"Unable to open marker file /OpenSim_Setup/.../S00_P00_T00_StaticTrial_filt_butterworth_0-12_LSTM.trc"

**Comment by davidpagnon** [comment]
Hi, sorry I'm realizing that the path to the file should be with Demo rather than DEMO. You can either manually look for your trc file, or reinstall it now: "pip install pose2sim -U"
